version: '3'
services:
  eureka-server:
    image: eureka-server-image
    build: ../EurekaServer
    container_name: eureka-server-container
    ports:
      - "8761:8761"
  billing-service:
    image: billing-service-image
    build: ../BillingService
    container_name: billing-service-container
    ports:
      - "8081:8081"
  order-service:
    image: order-service-image
    build: ../OrderService
    container_name: order-service-container
    ports:
      - "8082:8082"   
  angular-ui-service:
    image: angular-ui-service-image
    build: ../AngularUI/OSPRestaurantUI
    container_name: angular-ui-service-container
    ports:
      - "4200:4200"      