spring:
  application:
    name: billing-service

server:
  port: 8081


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/     #"eureka-server" service name in docker compose file. For local run, change to localhost
  instance: 
    preferIpAddress: true