spring:
  application:
    name: billing-service

server:
  port: 8081


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka/
  instance: 
    preferIpAddress: true